// Seed data for trucks (fallback when database is unavailable)
export const seedTrucks = [
  {
    id: 1,
    name: 'Tata Prima',
    manufacturer: 'Tata Motors',
    model: 'Prima',
    year: 2023,
    kilometers: 15000,
    horsepower: 380,
    price: 2850000,
    imageUrl: '/Gemini_Generated_Image_189xp8189xp8189x.png',
    subtitle: 'Premium heavy-duty truck with advanced features.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    name: 'Tata Signa',
    manufacturer: 'Tata Motors',
    model: 'Signa',
    year: 2022,
    kilometers: 22000,
    horsepower: 350,
    price: 3275000,
    imageUrl: '/Gemini_Generated_Image_6gr84a6gr84a6gr8.png',
    subtitle: 'Powerful and fuel-efficient tipper truck.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    name: 'Ashok Leyland 2820',
    manufacturer: 'Ashok Leyland',
    model: '2820',
    year: 2021,
    kilometers: 35000,
    horsepower: 200,
    price: 2480000,
    imageUrl: '/Gemini_Generated_Image_6q2b966q2b966q2b-2.png',
    subtitle: 'Reliable and durable for long hauls.',
    certified: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    name: 'BharatBenz 1617R',
    manufacturer: 'BharatBenz',
    model: '1617R',
    year: 2023,
    kilometers: 18000,
    horsepower: 170,
    price: 2690000,
    imageUrl: '/Gemini_Generated_Image_6q2b966q2b966q2b-3.png',
    subtitle: 'German engineering for Indian roads.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    name: 'Mahindra Bolero Pik-Up',
    manufacturer: 'Mahindra',
    model: 'Bolero Pik-Up',
    year: 2022,
    kilometers: 12000,
    horsepower: 75,
    price: 895000,
    imageUrl: '/Gemini_Generated_Image_6q2b966q2b966q2b.png',
    subtitle: 'Perfect for last-mile delivery.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    name: 'Mahindra Bolero Camper',
    manufacturer: 'Mahindra',
    model: 'Bolero Camper',
    year: 2023,
    kilometers: 8000,
    horsepower: 80,
    price: 945000,
    imageUrl: '/Gemini_Generated_Image_ex5b2aex5b2aex5b.png',
    subtitle: 'Versatile pickup for all terrains.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    name: 'Mahindra Pickup',
    manufacturer: 'Mahindra',
    model: 'Pickup',
    year: 2020,
    kilometers: 45000,
    horsepower: 70,
    price: 725000,
    imageUrl: '/Gemini_Generated_Image_azvzznazvzznazvz.png',
    subtitle: 'Economical and robust.',
    certified: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8,
    name: 'Eicher Pro 6025T',
    manufacturer: 'Eicher Motors',
    model: 'Pro 6025T',
    year: 2022,
    kilometers: 32000,
    horsepower: 250,
    price: 1975000,
    imageUrl: '/Gemini_Generated_Image_f5675rf5675rf567.png',
    subtitle: 'High payload capacity truck.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9,
    name: 'Force Urbania',
    manufacturer: 'Force Motors',
    model: 'Urbania',
    year: 2021,
    kilometers: 25000,
    horsepower: 115,
    price: 2850000,
    imageUrl: '/Gemini_Generated_Image_o2qgpno2qgpno2qg.png',
    subtitle: 'Premium passenger and cargo vehicle.',
    certified: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 10,
    name: 'Isuzu D-MAX',
    manufacturer: 'Isuzu',
    model: 'D-MAX',
    year: 2023,
    kilometers: 10000,
    horsepower: 150,
    price: 1890000,
    imageUrl: '/Gemini_Generated_Image_tywt8qtywt8qtywt.png',
    subtitle: 'Japanese quality pickup truck.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 11,
    name: 'Tata LPT 1613',
    manufacturer: 'Tata Motors',
    model: 'LPT 1613',
    year: 2022,
    kilometers: 20000,
    horsepower: 130,
    price: 2250000,
    imageUrl: '/Gemini_Generated_Image_wyesgowyesgowyes.png',
    subtitle: 'Versatile medium duty truck.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 12,
    name: 'SML Isuzu S7',
    manufacturer: 'SML Isuzu',
    model: 'S7',
    year: 2021,
    kilometers: 12000,
    horsepower: 92,
    price: 4290000,
    imageUrl: '/Gemini_Generated_Image_6q2b966q2b966q2b.png',
    subtitle: 'Heavy-duty tipper for mining.',
    certified: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

