// Seed data for trucks (fallback when database is unavailable)
// Updated with exact truck information from buy truck section
export const seedTrucks = [
  {
    id: 1,
    name: 'Eicher Pro 2110 LCV',
    manufacturer: 'Eicher Motors',
    model: 'Pro 2110 LCV',
    year: 2023,
    kilometers: 105453,
    horsepower: 110,
    price: 1680000,
    imageUrl: '/trucks/eicher-truck-1.webp',
    subtitle: 'Compact and efficient for city deliveries.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    name: 'Eicher Motors 1059 XP',
    manufacturer: 'Eicher Motors',
    model: '1059 XP',
    year: 2018,
    kilometers: 275034,
    horsepower: 100,
    price: 654500,
    imageUrl: '/trucks/truck3-image-2.png',
    subtitle: 'Reliable and fuel-efficient.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    name: 'Tata 1512 LPT',
    manufacturer: 'Tata Motors',
    model: '1512 LPT',
    year: 2021,
    kilometers: 67915,
    horsepower: 150,
    price: 209000,
    imageUrl: '/trucks/truck4-image-1.png',
    subtitle: 'Versatile medium duty truck.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    name: 'Eicher Pro 3015',
    manufacturer: 'Eicher Motors',
    model: 'Pro 3015',
    year: 2021,
    kilometers: 108084,
    horsepower: 150,
    price: 1150000,
    imageUrl: '/trucks/truck5-image-2.png',
    subtitle: 'Modern design with excellent fuel economy.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    name: 'Eicher Pro 3019',
    manufacturer: 'Eicher Motors',
    model: 'Pro 3019',
    year: 2021,
    kilometers: 75200,
    horsepower: 190,
    price: 2200000,
    imageUrl: '/trucks/truck6-image-2.jpg',
    subtitle: 'Powerful and efficient.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    name: 'Tata Motors 3518',
    manufacturer: 'Tata Motors',
    model: '3518',
    year: 2019,
    kilometers: 82085,
    horsepower: 180,
    price: 2805000,
    imageUrl: '/trucks/truck7-image-2.png',
    subtitle: 'Heavy-duty truck for long hauls.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    name: 'Eicher Pro 2110 XP',
    manufacturer: 'Eicher Motors',
    model: 'Pro 2110 XP',
    year: 2024,
    kilometers: 111339,
    horsepower: 110,
    price: 1705000,
    imageUrl: '/trucks/truck8-image-1.png',
    subtitle: 'Extended power variant for heavy loads.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8,
    name: 'Tata Motors Ultra T16',
    manufacturer: 'Tata Motors',
    model: 'Ultra T16',
    year: 2022,
    kilometers: 110312,
    horsepower: 160,
    price: 1155000,
    imageUrl: '/trucks/truck9-image-1.png',
    subtitle: 'Ultra-efficient commercial vehicle.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9,
    name: 'Tata LPT 1109 HEX 2',
    manufacturer: 'Tata Motors',
    model: 'LPT 1109 HEX 2',
    year: 2014,
    kilometers: 116432,
    horsepower: 109,
    price: 935000,
    imageUrl: '/trucks/truck10-image-1.jpg',
    subtitle: 'Efficient and reliable.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 10,
    name: 'Eicher Pro 2110 XP',
    manufacturer: 'Eicher Motors',
    model: 'Pro 2110 XP',
    year: 2019,
    kilometers: 230825,
    horsepower: 110,
    price: 1017500,
    imageUrl: '/trucks/truck11-image-1.png',
    subtitle: 'Extended power for demanding applications.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 11,
    name: 'Tata LPT 3118',
    manufacturer: 'Tata Motors',
    model: 'LPT 3118',
    year: 2015,
    kilometers: 232643,
    horsepower: 118,
    price: 1595000,
    imageUrl: '/trucks/truck12-image-1.png',
    subtitle: 'Powerful medium-duty truck.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 12,
    name: 'Eicher Pro 2118',
    manufacturer: 'Eicher Motors',
    model: 'Pro 2118',
    year: 2024,
    kilometers: 63529,
    horsepower: 118,
    price: 2172500,
    imageUrl: '/trucks/truck19-image-1.png',
    subtitle: 'Powerful and reliable.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 13,
    name: 'Ashok Leyland Partner 1114',
    manufacturer: 'Ashok Leyland',
    model: 'Partner 1114',
    year: 2023,
    kilometers: 56021,
    horsepower: 114,
    price: 1056000,
    imageUrl: '/trucks/truck14-image-1.png',
    subtitle: 'Reliable partner for your business.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 14,
    name: 'Ashok Leyland Partner 1615',
    manufacturer: 'Ashok Leyland',
    model: 'Partner 1615',
    year: 2022,
    kilometers: 125064,
    horsepower: 115,
    price: 1320000,
    imageUrl: '/trucks/truck15-image-1.png',
    subtitle: 'Powerful and durable.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 15,
    name: 'Eicher Pro 2114 XP',
    manufacturer: 'Eicher Motors',
    model: 'Pro 2114 XP',
    year: 2022,
    kilometers: 120421,
    horsepower: 114,
    price: 1475000,
    imageUrl: '/trucks/truck16-image-1.png',
    subtitle: 'Extended power for heavy loads.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 16,
    name: 'Ashok Leyland Ecomet 1214',
    manufacturer: 'Ashok Leyland',
    model: 'Ecomet 1214',
    year: 2019,
    kilometers: 350318,
    horsepower: 114,
    price: 1265000,
    imageUrl: '/trucks/truck17-image-1.png',
    subtitle: 'Eco-friendly and efficient.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 17,
    name: 'Eicher Pro 2059 XP',
    manufacturer: 'Eicher Motors',
    model: 'Pro 2059 XP',
    year: 2022,
    kilometers: 95421,
    horsepower: 59,
    price: 1455500,
    imageUrl: '/trucks/truck13-image-1.png',
    subtitle: 'Compact and efficient.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 18,
    name: 'Eicher Pro 2118',
    manufacturer: 'Eicher Motors',
    model: 'Pro 2118',
    year: 2024,
    kilometers: 45764,
    horsepower: 118,
    price: 164000,
    imageUrl: '/trucks/truck19-image-1.png',
    subtitle: 'Powerful and reliable.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 19,
    name: 'Tata 1613 CRI6',
    manufacturer: 'Tata Motors',
    model: '1613 CRI6',
    year: 2020,
    kilometers: 96023,
    horsepower: 113,
    price: 525000,
    imageUrl: '/trucks/truck20-image-1.png',
    subtitle: 'Advanced technology and efficiency.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 20,
    name: 'Eicher Pro 2059 XP',
    manufacturer: 'Eicher Motors',
    model: 'Pro 2059 XP',
    year: 2024,
    kilometers: 3111,
    horsepower: 59,
    price: 1595000,
    imageUrl: '/trucks/truck21-image-1.png',
    subtitle: 'Extended power variant.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 21,
    name: 'Tata 610',
    manufacturer: 'Tata Motors',
    model: '610',
    year: 2021,
    kilometers: 51327,
    horsepower: 100,
    price: 1200000,
    imageUrl: '/trucks/truck22-image-1.png',
    subtitle: 'Versatile commercial vehicle.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 22,
    name: 'Ashok Leyland Ecomet 1212',
    manufacturer: 'Ashok Leyland',
    model: 'Ecomet 1212',
    year: 2018,
    kilometers: 196243,
    horsepower: 112,
    price: 1000000,
    imageUrl: '/trucks/truck17-image-1.png',
    subtitle: 'Eco-friendly and efficient.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 23,
    name: 'Eicher Pro 3015 XP',
    manufacturer: 'Eicher Motors',
    model: 'Pro 3015 XP',
    year: 2023,
    kilometers: 85017,
    horsepower: 150,
    price: 2100000,
    imageUrl: '/trucks/truck5-image-2.png',
    subtitle: 'Extended power with modern features.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 24,
    name: 'SML Isuzu Samrat GS',
    manufacturer: 'SML Isuzu',
    model: 'Samrat GS',
    year: 2020,
    kilometers: 16024,
    horsepower: 92,
    price: 850000,
    imageUrl: '/trucks/truck25-image-1.png',
    subtitle: 'Japanese quality and reliability.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 25,
    name: 'Eicher Pro 2059 XP',
    manufacturer: 'Eicher Motors',
    model: 'Pro 2059 XP',
    year: 2021,
    kilometers: 52012,
    horsepower: 59,
    price: 850000,
    imageUrl: '/trucks/truck13-image-1.png',
    subtitle: 'Compact and efficient.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 26,
    name: 'Eicher Pro 2059 XP',
    manufacturer: 'Eicher Motors',
    model: 'Pro 2059 XP',
    year: 2022,
    kilometers: 72154,
    horsepower: 59,
    price: 900000,
    imageUrl: '/trucks/truck21-image-1.png',
    subtitle: 'Extended power variant.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 27,
    name: 'Tata 709 LPT',
    manufacturer: 'Tata Motors',
    model: '709 LPT',
    year: 2021,
    kilometers: 87421,
    horsepower: 70,
    price: 825000,
    imageUrl: '/trucks/truck28-image-1.png',
    subtitle: 'Light commercial vehicle.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 28,
    name: 'Tata 709 G LPT',
    manufacturer: 'Tata Motors',
    model: '709 G LPT',
    year: 2022,
    kilometers: 83921,
    horsepower: 70,
    price: 1100000,
    imageUrl: '/trucks/truck29-image-1.png',
    subtitle: 'Upgraded light commercial vehicle.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 29,
    name: 'Tata 1109 G LPT',
    manufacturer: 'Tata Motors',
    model: '1109 G LPT',
    year: 2020,
    kilometers: 87631,
    horsepower: 109,
    price: 1150000,
    imageUrl: '/trucks/truck30-image-1.png',
    subtitle: 'Reliable medium-duty truck.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 30,
    name: 'Tata 1512 LPT',
    manufacturer: 'Tata Motors',
    model: '1512 LPT',
    year: 2022,
    kilometers: 73542,
    horsepower: 150,
    price: 1500000,
    imageUrl: '/trucks/truck31-image-1.png',
    subtitle: 'Versatile medium duty truck.',
    certified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]
